### ISSUE TITLE
Branch with global stack

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#101]
In a separate branch, be closer to the previous functioning having only one global stack:
- [x] only one stack for the app instead of one per tab
- [x] the stack is updated only when the user selects a stack
- [x] next/previous entity buttons apears only if the current tab's entity is inside the current stack

Bonus:
- [x] when the number of entities from the hyphe status differs from the current stack's total results, add a refresh stack button within the inquiry overview
- [x] when the current tab's entity in not in the current stack, add a button inside the inquiry overview to load the good stack (see with @robindemourat how... ;) )
- [x] find a way to display within the "Browsed webentity" tab in which stack we currently are
- [x] automatically switch to "Browsed webentity" tab when selecting an entity (only the first after stack's load?) from the stack in "Inquiry overview"

**Comment by mydu** [comment]
check branch https://github.com/medialab/hyphe-browser/tree/global-stack

**Comment by robindemourat** [comment]
I scaffolded a new design attempt of this version in branch `redesign-global-stack-2` to review together.

* the "source of truth" for next and previous is always the list selected in `inquiry overview`
* navigating in the browser does not change the `inquiry overview`'s selected stack
* added multiple visual cues concerning the current stack and the currently browsed webentity's status
* in `inquiry overview`, added a `locate` button which switches the current stack to currently browsed webentity's stack and scrolls to related webentity card when possible

NB : it needs one improvement to be completely testable: when the currently browsed entity is not in the  related stack's list of entities, it should be added to be visible when clicking on the "locate" button in the inquiry overview.

NB2 : "refresh" button not yet implemented (might be complex because of filters+pagination but would be a great feature)
