### ISSUE TITLE
[tags cartel] Tag values should be editable

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#114]
When clicking on an existing value within a tag category, the text appears but is not editable, one can only choose another tag value or type a new one from scratch whereas it should be like most inputs an editable version of the existing tag

**Comment by boogheta** [comment]
Remnant fixes:
- [ ] when emptying the value, the placeholder shows the original tag
- [ ] sometimes while editing, the tag value gets emptied
- [ ] when trying to set a shorter version of a same tag (for instance change aaa to aa) the autocompletion automatically takes the existing version instead of the new one
- [ ] it would be nice to be able when editing to clear it using del/backspace then enter, currently it does not

**Comment by mydu** [comment]
some issues might be auto-fixed if those pull requests are approved by `react-select`
* when trying to set a shorter version of a same tag (for instance change aaa to aa) the autocompletion automatically takes the existing version instead of the new one - https://github.com/JedWatson/react-select/pull/4080
* when emptying the value, the placeholder shows the original tag - https://github.com/JedWatson/react-select/issues/3821

**Comment by boogheta** [comment]
Great, looks like the first one should be quickly merged looking at the comments
The second one is only an issue though and a little bit old. Do you think it's doable quickly to try and fix it ourselves?
