### ISSUE TITLE
Handle changes of webentity within the same domain

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#161]
If I have two hierarchic webentities (for instance sciencespo.fr and sciencespo.fr/cevipof) and I move from the biggest to the second, the current webentity does not get updated and still reports to be in the biggest. declare_page should be used in more cases than presently to fix this.
A possible option to keep avoiding the call everytime would be:
- when we load a new webentity, start loading in the background the list of its child_webentities
- during that time, call declare_page always even for changes within the same domain
- stop the pending call if we leave the webentity?
- when it is loaded, call declare_page for changes within the same domain only if the new url does belong to a child webentity

There might be better solutions...

**Comment by mydu** [comment]
this should be fixed in #124 
but there are cases that webentity's `referrers/referrals/paginate_pages` could not be updated

1. set uncrawled webentity to "IN" and start crawling, currently there is no response when it finished until manually call `declare_page` to get the `crawling_status`
2. change prefix of an exist crawled webentity and re-crawl it, same issue cause when way to know when it will finish

need to add api call in `CorpusStatusWatcher` to get this information,  probably https://github.com/medialab/hyphe/blob/master/doc/api.md#basic-crawl-methods @boogheta
