### ISSUE TITLE
Unhandled usecases for redirections

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#173]
When testing with the following usecase which trigger the redirection in JS after a few seconds : https://controverses.sciences-po.fr/sdfsdfsdfs 
It makes me realise, in this case we might want to actually do two other options which are not possible with the current modal:
- [x] put Controverses.org as a whole within Sciencespo.fr, which the slider in the third option does not permit, so the slider should allow to go further to the root 
- [x] put just a part of Sciencespo.fr Controverses.org, so that means setting up the same slider in the second option as in the third
- [x] reorder the put as OUT as third choice
- [x] actually do nothing, just visit the webentity we're redirected to while keeping the other as such

Does that make sense to you @robindemourat ?

(follow up #22 #124 #126)

**Comment by mydu** [comment]
@boogheta option1 and option2 (in the mock-up) can be considered as a same option if we allow the slider to the root ? Otherwise, we need to hide option 2 if original url is on the root page (for example the cevipof.com case) ?

![Screenshot from 2020-12-04 16-05-01](https://user-images.githubusercontent.com/3991275/101179624-c5dce500-364a-11eb-82dd-338dceeaf5de.png)

**Comment by RouxRC** [comment]
Yes they should be merged by allowing the slider to the root!
