### ISSUE TITLE
AutoBuilds might break following GHActions upgrade to node20

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#224]
cf https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
cc @Guillaume-Levrier

**Comment by Guillaume-Levrier** [comment]
in `build.yml`you can try to change
-actions/checkout@v2 -> actions/checkout@v**4**
-actions/setup-node@v2 -> actions/setup-node@v**4**

I'm running into other problems with the building of my electron app but those might be unrelated / problems you don't have.

**Comment by boogheta** [comment]
great, thx!

**Comment by Guillaume-Levrier** [comment]
New issue since early May 2024

> **homebrew/cask-versions was deprecated**

Solution could be to replace `homebrew/cask-versions` -> `homebrew/cask` in the same build.yml file.

**Comment by Guillaume-Levrier** [comment]
You also might want to:
- update the devDependency (in `package.json`)  **"cross-env": "^7.0.3"**
- change `bin/package.js` at the level of the `targets` array and make sure the windows object has a name property that is not just "Windows" but something like  `name: "Windows-64bit"`
- update the end of the build.yml file with `[NAME]-Windows-64bit.zip` instead of what was there before (`[NAME]-Windows.zip`)
