### ISSUE TITLE
Tag categories bug 

### ISSUE THREAD

**Issue by paulgirard** [medialab/hyphe-browser#6]
To replicate : 
- on a Linux OS (I tried Ubuntu 12.04 and Mint 17.1)
- download last release
- connect to a corpus
- add a category of tags

Then the category UI module appears just a second and then disappear totally.

**Comment by boogheta** [comment]
I got an understanding of the problem and why it didn't show before.
What happens is the list of categories displayed is refreshed every time we refreshed the tag categories from server side. In dev mode the refresh rate is every 30 secs instead of every sec in production so the bug was hardly detectable then as the user had the time to enter a tag value after proposing a category, but in production the user can never send a value as categories without the new proposed ones are refreshed.

I imagine two ways of fixing this: 
- one would be to load categories from server once and only once at the opening of the corpus as new created ones can be added in ram along the way. This has the inconvenient of not handling multiusers working on the same corpus simultaneously
- the other would be to handle the display of the new categories still in the process of creation separately from the others, hence not removing them when existing categories are refreshed.
I guess the second is better, but I'm not sure where to deal with that in the code, @naholyr could you point me in the right direction?
