### ISSUE TITLE
Rename Prospection

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe-browser#60]
Feedbacks from user tests reveal people don't really understand the "Prospection" wording for the discovered entities.

During our meeting our discussion lead to the following proposition instead (for HyBro only so far, but we could discuss it later on for Hyphe as well if we feel it's useful) : 
- in english : "To review"
- in french : "À traiter"

I feel like we should go on, but I want to be sure people behind the original wordings agree, so let's wait for @thomastari @jacomyma & @paulgirard 's opinions before actually doing it !
cc @robindemourat @audreybaneyx @Yomguithereal @mydu

**Comment by jacomyma** [comment]
Overall I like it, but I have a reserve.

I feel like it is indeed more explicit, because the wording is more relatable. However it lacks the notion that what you review is not the entity itself but its belonging to the corpus. I dislike that it seems to imply that the user must review all discovered entities exhaustively. I preferred the notion that discovered entities were _suggested_ to the user.

My feeling is that "To review" / "À traiter" is good enough in contexts where we need a short label, but that we should make clear that it is just a recommendation system, where we have more room for explanations. For instance by using the title "Recommendations to review" / "Propositions à traiter".

**Comment by boogheta** [comment]
Very good point, I didn't think about it but indeed "to review" suggests the user should always go through all of them and not only review some until some point. It's well appropriated for "To tag", but indeed more problematic for discovered entities to prospect. So I end up with the same reservations and feel like there is probably still another better wording to find. All other ideas welcome!

Here are a few:
- Candidates
- Recommendations
- Propositions
- Suggestions
- Found (même problème que Discovered probablement)

**Comment by jacomyma** [comment]
I like suggestions, recommendations and propositions (the words, not the concepts -_-')

I bet that people have the experience of a [recommendation engine](https://whatis.techtarget.com/definition/recommendation-engine) and could reinvest that knowledge to understand what it does. Then "recommendation" is the best choice. But I am not sure that users know the _term_ "recommendation engine". Still, we might enforce this vocabulary.

**Comment by boogheta** [comment]
Let's go with Suggestions/suggested for now
